/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package css337walletassignment;

import java.math.BigInteger;
import javax.swing.*;

/**
 *
 * @author Michael
 */
public class ReceiveEMDMenu extends javax.swing.JFrame {
    JFrame previousMenu;
    
    /**
     * Creates new form ReceiveEMDMenu
     */
    public ReceiveEMDMenu(JFrame previousMenu) {
        this.previousMenu = previousMenu;
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtFldEncryptedEMD = new javax.swing.JTextField();
        BtnConfirmDeposit = new javax.swing.JButton();
        BtnReturnToPreviousMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtFldEncryptedEMD.setText("Encrypted EMD...");

        BtnConfirmDeposit.setText("Confirm Deposit");
        BtnConfirmDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnConfirmDepositActionPerformed(evt);
            }
        });

        BtnReturnToPreviousMenu.setText("<---");
        BtnReturnToPreviousMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReturnToPreviousMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(TxtFldEncryptedEMD, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnConfirmDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addComponent(BtnReturnToPreviousMenu)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BtnReturnToPreviousMenu)
                .addGap(28, 28, 28)
                .addComponent(TxtFldEncryptedEMD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnConfirmDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConfirmDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConfirmDepositActionPerformed
        String encryptedEMD = TxtFldEncryptedEMD.getText();
        
        byte[] decryptedAmount; 
        
        decryptedAmount = AES256Encrypter.decrypt(encryptedEMD, User.PERSONAL_WALLET_KEY);
        
        BigInteger result = new BigInteger(decryptedAmount);
        
        try {
            User.PERSONAL_BALANCE.add(result.intValueExact());
        }
        catch(Exception e) {
            JOptionPane.showMessageDialog(this, "The input EMD isn't a valid amount", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnConfirmDepositActionPerformed

    private void BtnReturnToPreviousMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReturnToPreviousMenuActionPerformed
        this.setVisible(false);
        
        previousMenu.setVisible(true);
    }//GEN-LAST:event_BtnReturnToPreviousMenuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnConfirmDeposit;
    private javax.swing.JButton BtnReturnToPreviousMenu;
    private javax.swing.JTextField TxtFldEncryptedEMD;
    // End of variables declaration//GEN-END:variables
}
